interface Case {
  id: string;
  hasPawn: boolean;
  color: boolean;
  idPion: string;
  team: string;
}

const initialDamier: Case[] = [
  { team:"a", id: "1", hasPawn: true, color: true, idPion: "A1" },
  { team:"a", id: "2", hasPawn: false, color: false, idPion: "" },
  { team:"a", id: "3", hasPawn: true, color: true, idPion: "A2" },
  { team:"a", id: "4", hasPawn: false, color: false, idPion: "" },
  { team:"a", id: "5", hasPawn: true, color: true, idPion: "A3" },
  { team:"a", id: "6", hasPawn: false, color: false, idPion: "" },
  { team:"a", id: "7", hasPawn: true, color: true, idPion: "A4" },
  { team:"a", id: "8", hasPawn: false, color: false, idPion: "" },
  { team:"a", id: "9", hasPawn: true, color: true, idPion: "A5" },
  { team:"a", id: "10", hasPawn: false, color: false, idPion: "" },

  { team:"a", id: "11", hasPawn: false, color: false, idPion: "" },
  { team:"a", id: "12", hasPawn: true, color: true, idPion: "A6" },
  { team:"a", id: "13", hasPawn: false, color: false, idPion: "" },
  { team:"a", id: "14", hasPawn: true, color: true, idPion: "A7" },
  { team:"a", id: "15", hasPawn: false, color: false, idPion: "" },
  { team:"a", id: "16", hasPawn: true, color: true, idPion: "A8" },
  { team:"a", id: "17", hasPawn: false, color: false, idPion: "" },
  { team:"a", id: "18", hasPawn: true, color: true, idPion: "A9" },
  { team:"a", id: "19", hasPawn: false, color: false, idPion: "" },
  { team:"a", id: "20", hasPawn: true, color: true, idPion: "A10" },

  {team:"", id: "21", hasPawn: false, color: true, idPion: "" },
  {team:"", id: "22", hasPawn: false, color: false, idPion: "" },
  {team:"", id: "23", hasPawn: false, color: true, idPion: "" },
  {team:"", id: "24", hasPawn: false, color: false, idPion:"" },
  {team:"", id: "25", hasPawn: false, color: true, idPion: "" },
  {team:"", id: "26", hasPawn: false, color: false, idPion: "" },
  {team:"", id: "27", hasPawn: false, color: true, idPion: "" },
  {team:"", id: "28", hasPawn: false, color: false, idPion: "" },
  {team:"", id: "29", hasPawn: false, color: true, idPion: "" },
  {team:"", id: "30", hasPawn: false, color: false, idPion: "" },

  {team:"", id: "31", hasPawn: false, color: false, idPion: "" },
  {team:"", id: "32", hasPawn: false, color: true, idPion: "" },
  {team:"", id: "33", hasPawn: false, color: false, idPion: "" },
  {team:"", id: "34", hasPawn: false, color: true, idPion: "" },
  {team:"", id: "35", hasPawn: false, color: false, idPion: "" },
  {team:"", id: "36", hasPawn: false, color: true, idPion: "" },
  {team:"", id: "37", hasPawn: false, color: false, idPion: "" },
  {team:"", id: "38", hasPawn: false, color: true, idPion: "" },
  {team:"", id: "39", hasPawn: false, color: false, idPion: "" },
  {team:"", id: "40", hasPawn: false, color: true, idPion: "" },

  {team:"", id: "41", hasPawn: false, color: true, idPion: "" },
  {team:"", id: "42", hasPawn: false, color: false, idPion: "" },
  {team:"", id: "43", hasPawn: false, color: true, idPion: "" },
  {team:"", id: "44", hasPawn: false, color: false, idPion: "" },
  {team:"", id: "45", hasPawn: false, color: true, idPion: "" },
  {team:"", id: "46", hasPawn: false, color: false, idPion: "" },
  {team:"", id: "47", hasPawn: false, color: true, idPion: "" },
  {team:"", id: "48", hasPawn: false, color: false, idPion: "" },
  {team:"", id: "49", hasPawn: false, color: true, idPion: "" },
  {team:"", id: "50", hasPawn: false, color: false, idPion: "" },

  {team:"", id: "51", hasPawn: false, color: false, idPion: "" },
  {team:"", id: "52", hasPawn: false, color: true, idPion: "" },
  {team:"", id: "53", hasPawn: false, color: false, idPion: "" },
  {team:"", id: "54", hasPawn: false, color: true, idPion: "" },
  {team:"", id: "55", hasPawn: false, color: false, idPion: "" },
  {team:"", id: "56", hasPawn: false, color: true, idPion: "" },
  {team:"", id: "57", hasPawn: false, color: false, idPion: "" },
  {team:"", id: "58", hasPawn: false, color: true, idPion: "" },
  {team:"", id: "59", hasPawn: false, color: false, idPion: "" },
  {team:"", id: "60", hasPawn: false, color: true, idPion: "" },

  {team:"", id: "61", hasPawn: false, color: true, idPion: "" },
  {team:"", id: "62", hasPawn: false, color: false, idPion: "" },
  {team:"", id: "63", hasPawn: false, color: true, idPion: "" },
  {team:"", id: "64", hasPawn: false, color: false, idPion: "" },
  {team:"", id: "65", hasPawn: false, color: true, idPion: "" },
  {team:"", id: "66", hasPawn: false, color: false, idPion: "" },
  {team:"", id: "67", hasPawn: false, color: true, idPion: "" },
  {team:"", id: "68", hasPawn: false, color: false, idPion: "" },
  {team:"", id: "69", hasPawn: false, color: true, idPion: "" },
  {team:"", id: "70", hasPawn: false, color: false, idPion: "" },

  {team:"", id: "71", hasPawn: false, color: false, idPion: "" },
  {team:"", id: "72", hasPawn: false, color: true, idPion: "" },
  {team:"", id: "73", hasPawn: false, color: false, idPion: "" },
  {team:"", id: "74", hasPawn: false, color: true, idPion: "" },
  {team:"", id: "75", hasPawn: false, color: false, idPion: "" },
  {team:"", id: "76", hasPawn: false, color: true, idPion: "" },
  {team:"", id: "77", hasPawn: false, color: false, idPion: "" },
  {team:"", id: "78", hasPawn: false, color: true, idPion: "" },
  {team:"", id: "79", hasPawn: false, color: false, idPion: "" },
  {team:"", id: "80", hasPawn: false, color: true, idPion: "" },

  {team:"b", id: "81", hasPawn: true, color: true, idPion: "B6" },
  {team:"b", id: "82", hasPawn: false, color: false, idPion: "" },
  {team:"b", id: "83", hasPawn: true, color: true, idPion: "B7" },
  {team:"b", id: "84", hasPawn: false, color: false, idPion: "" },
  {team:"b", id: "85", hasPawn: true, color: true, idPion: "B8" },
  {team:"b", id: "86", hasPawn: false, color: false, idPion: "" },
  {team:"b", id: "87", hasPawn: true, color: true, idPion: "B9" },
  {team:"b", id: "88", hasPawn: false, color: false, idPion: "" },
  {team:"b", id: "89", hasPawn: true, color: true, idPion: "B10" },
  {team:"b", id: "90", hasPawn: false, color: false, idPion: "" },

  {team:"b", id: "91", hasPawn: false, color: false, idPion: "" },
  {team:"b", id: "92", hasPawn: true, color: true, idPion: "B1" },
  {team:"b", id: "93", hasPawn: false, color: false, idPion: "" },
  {team:"b", id: "94", hasPawn: true, color: true, idPion: "B2" },
  {team:"b", id: "95", hasPawn: false, color: false, idPion: "" },
  {team:"b", id: "96", hasPawn: true, color: true, idPion: "B3" },
  {team:"b", id: "97", hasPawn: false, color: false, idPion: "" },
  {team:"b", id: "98", hasPawn: true, color: true, idPion: "B4" },
  {team:"b", id: "99", hasPawn: false, color: false, idPion: "" },
  {team:"b", id: "100", hasPawn: true, color: true, idPion: "B5" },
  // Ajoute d'autres cases selon ton damier
];

export default initialDamier;